MAX_FPS = 60
SHOW_FPS = True

WIDTH = 768
HEIGHT = 768

NB_ROBOTS = 25
ROBOT_MAX_SPEED = 4
ROBOT_MAX_FORCE = 0.05
ROBOT_SEPARATION_DIST = 30
ROBOT_NEIGHBOR_DIST = 30
ROBOT_BOUNCE = 0.5
ROBOT_BODY_ANIMATION_SCALAR = 14

CONTROL_SPEED = 5

TILEMAP_WIDTH = 6
TILEMAP_HEIGHT = 6
TILE_SIZE = 128

# in seconds
LEVEL_PERIOD_MAX = 40
LEVEL_PERIOD_MIN = 2
LEVEL_PERIOD_MALUS = 2

LEVEL_WEIGHT_EASY = 8
LEVEL_WEIGHT_NORMAL = 3
LEVEL_WEIGHT_HARD = 1


if __name__ == "__main__":
    import main